# Generated by Django 5.0.6 on 2024-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='brand',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='model',
        ),
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(upload_to='watches_images/'),
        ),
    ]
